# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7
python: 3.7.1

# Installing requirements
install:
  - sudo apt-get install python3.7-dev
  - pip3 install dbus-python
  - pip3 install -r requirements.txt

# Run the unit test
script:
- python3 fdn.py -v
